### ISSUE TITLE
docpad upgrade doesn't work

### ISSUE THREAD

**Issue by drguildo** [docpad/documentation#153]
I'm running Windows 7 64-bit and npm 2.5.1. When I do `docpad upgrade` it seems to work but then when I do `docpad run` it tells me a new version is available.

**Comment by Greduan** [comment]
@drguildo There is a difference between project-wide DocPad (which is what `docpad upgrade` updates) and computer-wide DocPad (which is what you install with `[sudo] npm update -g docpad`).

That makes me think that the problem you're running into is that the global version is out of date and it's letting you know about that.

**Comment by drguildo** [comment]
I think you're right. Question is why do I have an old global version when I just followed the install instructions? Are they out of date?

**Comment by Greduan** [comment]
DocPad gets updates very often when @balupton is active. Sometimes several updates a day.

**Comment by balupton** [comment]
`docpad upgrade` is for the global version of docpad, `docpad update` is for the local version of docpad and the local plugins. The upgrade instructions should tell you to do both...

**Comment by Greduan** [comment]
Oh OK. I forgot the DocPad command has a command to update both. Sorry bout that @drguildo. orz

**Comment by Zearin** [comment]
> docpad upgrade is for the global version of docpad, docpad update is for the local version of docpad and the local plugins. The upgrade instructions should say to do both...

That’s really confusing.  I don’t think DocPad should use a different command for the same operation, just because it works on a different scope.  

Can’t you just make it `docpad update [--global]`, and use the command-line flag to determine the scope?

**Comment by Greduan** [comment]
I agree with Zearin. Although it is my idea an update command isn't needed at all. :)

**Comment by balupton** [comment]
> Can’t you just make it docpad update [--global], and use the command-line flag to determine the scope?

Maybe. The issue is that `--global` says run the global installation, whereas in that case, it would say update the global installation.
